import type { Metadata } from "next";
import { Geist, Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const meeriweather = Merriweather_Sans({
  variable: "--font-merriweather_sans",
  subsets: ["latin", 'latin-ext'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Astro_HR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${meeriweather.variable} antialiased`}
      >
        <Header title="Logo" />
        {children}
      </body>
    </html>
  );
}
