import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer/Page";
import Breadcrumbs from "@/components/Breadcrumbs";

const merriweather = Merriweather_Sans({
  variable: "--font-merriweather_sans",
  subsets: ["latin", 'latin-ext'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Astro_HR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} antialiased`}
      >
        <div className="bg-gradient-to-b absolute w-full from-[#cde6ff] to-[#fff] h-96 pt-3">
          <Header className="" title="Logo" />
          {children}  
          <Footer />
        </div>
      </body>
    </html>
  );
}
