import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer/Page";
import Breadcrumbs from "@/components/Breadcrumbs";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const merriweather = Merriweather_Sans({
  variable: "--font-merriweather_sans",
  subsets: ["latin", 'latin-ext'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Astro_HR",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${merriweather.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <div className="bg-gradient-to-b absolute w-full from-[#cde6ff] to-[#fff] h-96 pt-3"> 
            <Header className="" title="Logo" />
            {children}  
            <Footer /> 
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
